name: flutterdex
description: Flutterdex is an application to demonstrate widgets available in Flutter.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  collection: ^1.17.2
  device_frame: ^1.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.7+1
  flutter_animate: ^4.2.0+1
  flutter_highlighter: ^0.1.1
  flutter_riverpod: ^2.4.5
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  highlight: ^0.7.0
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  package_info_plus: ^4.2.0
  riverpod_annotation: ^2.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
      ref: 6c66ad2

dev_dependencies:
  build_runner: ^2.4.6
  choco_lints:
    git:
      ref: main
      url: git@github.com:charlescyt/choco_lints.git
  custom_lint: ^0.5.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - lib/features/flutter_widget/demos/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Black.ttf

    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
